// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimilarityChecker.Api.Data;

#nullable disable

namespace SimilarityChecker.Api.Migrations
{
    [DbContext(typeof(SimilarityCheckerDbContext))]
    [Migration("20260208205952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.MatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocEnd")
                        .HasColumnType("int");

                    b.Property<int>("DocStart")
                        .HasColumnType("int");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MatchType")
                        .HasColumnType("int");

                    b.Property<Guid>("OnlineSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("SourceEnd")
                        .HasColumnType("int");

                    b.Property<int>("SourceStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OnlineSourceId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.OnlineSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("OnlineSources");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.ReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.SearchQueryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("SearchQueries");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.SearchResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<Guid>("SearchQueryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Snippet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SearchQueryId");

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.MatchEntity", b =>
                {
                    b.HasOne("SimilarityChecker.Api.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Matches")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimilarityChecker.Api.Data.Entities.OnlineSourceEntity", "OnlineSource")
                        .WithMany("Matches")
                        .HasForeignKey("OnlineSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("OnlineSource");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.ReportEntity", b =>
                {
                    b.HasOne("SimilarityChecker.Api.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Reports")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.SearchQueryEntity", b =>
                {
                    b.HasOne("SimilarityChecker.Api.Data.Entities.DocumentEntity", "Document")
                        .WithMany("SearchQueries")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.SearchResultEntity", b =>
                {
                    b.HasOne("SimilarityChecker.Api.Data.Entities.SearchQueryEntity", "SearchQuery")
                        .WithMany("Results")
                        .HasForeignKey("SearchQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchQuery");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Reports");

                    b.Navigation("SearchQueries");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.OnlineSourceEntity", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SimilarityChecker.Api.Data.Entities.SearchQueryEntity", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
